##########################
## slame theme settings ##
##########################

# Theme version
version: 1.0.0

# Header
menu:
  - page: home
    directory: .
    icon: fa-home
  - page: archive
    directory: archives/
    icon: fa-archive
  - page: about
    directory: about/
    icon: fa-user
  - page: rss
    directory: atom.xml
    icon: fa-rss

js: js
css: css

render:
  ts: source/js/tsconfig.json

# mathjax
mathjax:
    enable: true
    cdn: //cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.7/MathJax.js?config=TeX-MML-AM_CHTML

# github markdown css
markdown_css:
    enable: true
    cdn: //cdnjs.cloudflare.com/ajax/libs/github-markdown-css/4.0.0/github-markdown.min.css

# highlight
highlight:
    enable: true
    css_cdn: //cdnjs.cloudflare.com/ajax/libs/highlight.js/10.1.2/styles/default.min.css

# font awesome
font_awesome:
    cdn: //cdnjs.cloudflare.com/ajax/libs/font-awesome/5.14.0/css/all.min.css

# github
github:
    url: https://github.com/

beian:
    enable: true
    link: https://beian.miit.gov.cn
    icp: "000000000"

